title: Minced Words
subtitle: ""
description: A spoken word podcast of dramatic perormances
author:
    name: Dan Jones
    email: danjones@goodevilgenius.org

keywords:
    - podcast
    - spoken word
    - dramatic
    - performance

categories:
    - name: Arts
      children:
        - name: Performing Arts
    - name: Comedy
    - name: "News & Politics"
      children:
        - name: "Religion & Spirituality"
          children:
            - name: Other

url: https://danjones000.gitlab.io
root: /minced-words

pagination:
    per_page: 10
